#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := CubeeEnergy
EXTRA_COMPONENT_DIRS ?= $(PROJECT_PATH)/components/drv $(PROJECT_PATH)/components/app $(PROJECT_PATH)/components/svc $(PROJECT_PATH)/components/util
include $(IDF_PATH)/make/project.mk



